WebApp/main/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Email


class ContactForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired(), Email()])
    phone = StringField("Phone", validators=[DataRequired()])
    subject = StringField("Subject", validators=[DataRequired()])
    message = TextAreaField("Message", validators=[DataRequired()])
    recaptcha = RecaptchaField()
    submit = SubmitField("Send")


class NewsletterForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Subscribe")

WebApp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")

WebApp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_admin import Admin
from WebApp.config import Config
from WebApp.admin import MyAdminIndexView, ModelView

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message_category = "info"
mail = Mail()
admin = Admin(index_view=MyAdminIndexView())

from WebApp.models import *


def create_app(config_class=Config):

    app = Flask(__name__)
    app.url_map.strict_slashes = False
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    admin.init_app(app)
    with app.app_context():
        db.create_all()

    admin.add_view(ModelView(Subscriber, db.session))
    admin.add_view(ModelView(User, db.session))
    admin.add_view(ModelView(Post, db.session))
    admin.add_view(ModelView(Product, db.session))
    admin.add_view(ModelView(Cart, db.session))
    admin.add_view(ModelView(Item, db.session))
    admin.add_view(ModelView(Order, db.session))

    from WebApp.main.routes import main_blueprint
    from WebApp.users.routes import users_blueprint
    from WebApp.posts.routes import posts_blueprint
    from WebApp.store.routes import store_blueprint
    from WebApp.errors.handlers import errors

    app.register_blueprint(main_blueprint)
    app.register_blueprint(users_blueprint)
    app.register_blueprint(posts_blueprint)
    app.register_blueprint(store_blueprint)
    app.register_blueprint(errors)

    return app

WebApp/main/routes.py
from WebApp.models import Subscriber
from WebApp import db

from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_login import current_user
from WebApp.main.forms import ContactForm
from WebApp.main.utils import handle_contact_message

main_blueprint = Blueprint("main", __name__, template_folder="templates")


@main_blueprint.route("/")
def home():
    return render_template("main/index.html", title="Home")


@main_blueprint.route("/marketing")
def marketing():
    return render_template("main/marketing.html", title="Marketing")


@main_blueprint.route("/contact", methods=["GET", "POST"])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        handle_contact_message()
        flash(f"Your message has been sent.", "success")
        return redirect(url_for("main.home"))
    return render_template("main/contact.html", title="Contact", form=form)


@main_blueprint.route("/subscribe_to_newsletter", methods=["POST"])
def subscribe_to_newsletter():
    email = request.form["email"]
    if not Subscriber.query.filter_by(email=email).first():
        subscriber = Subscriber(email=email)
        db.session.add(subscriber)
        db.session.commit()
        flash(f"You are now subscribed to the newsletter, {email}", "success")
    else:
        flash("Already subbed.", "danger")
    return redirect(request.referrer)

WebApp/posts/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from WebApp.posts.forms import PostForm
from WebApp.posts.utils import (
    add_post,
    get_paginated_posts,
    get_paginated_search_posts,
    get_post,
    update_post,
    delete_post,
    get_redirects,
)

posts_blueprint = Blueprint(
    "posts", __name__, url_prefix="/posts", template_folder="templates"
)

# Create


@posts_blueprint.route("/add", methods=["POST"])
def add_post_route():
    form = PostForm()
    if form.validate_on_submit():
        add_post()
        flash("Post has been created.", "success")
        return redirect(request.form["url"])


# Read


@posts_blueprint.route("", methods=["GET", "POST"])
def posts():
    create_post_form = PostForm()
    if create_post_form.validate_on_submit():
        add_post()
        return redirect(request.form["url"])
    posts = get_paginated_posts()
    update_post_form = PostForm()
    redirect_dict = get_redirects()
    return render_template(
        "posts/posts/view.html",
        title="Posts",
        create_post_form=create_post_form,
        update_post_form=update_post_form,
        create_redirect=redirect_dict["create"],
        update_redirect=redirect_dict["update"],
        delete_redirect=redirect_dict["delete"],
        posts=posts,
    )


@posts_blueprint.route("/search", methods=["POST"])
def search():
    if request.method == "POST":
        search_string = request.form["search"]
    return redirect(url_for("posts.get_search", search_string=search_string))


@posts_blueprint.route("/search/<string:search_string>", methods=["GET"])
def get_search(search_string):
    posts = get_paginated_search_posts(search_string)
    create_post_form = PostForm()
    update_post_form = PostForm()
    redirect_dict = get_redirects(search_string=search_string)
    return render_template(
        "posts/posts/view.html",
        title="Posts",
        create_post_form=create_post_form,
        update_post_form=update_post_form,
        create_redirect=redirect_dict["create"],
        update_redirect=redirect_dict["update"],
        delete_redirect=redirect_dict["delete"],
        posts=posts,
        search_string=search_string,
    )


@posts_blueprint.route("/<int:post_id>", methods=["GET"])
def post(post_id):
    post = get_post(post_id)
    create_post_form = PostForm()
    update_post_form = PostForm()
    update_post_form.title.data = post.title
    update_post_form.content.data = post.content
    redirect_dict = get_redirects(post_id=post_id)
    return render_template(
        "posts/post/view.html",
        title=post.title,
        create_post_form=create_post_form,
        update_post_form=update_post_form,
        create_redirect=redirect_dict["create"],
        update_redirect=redirect_dict["update"],
        delete_redirect=redirect_dict["delete"],
        post=post,
    )


# Update


@posts_blueprint.route("/<int:post_id>/update", methods=["POST"])
def update_post_route(post_id):
    post = get_post(post_id)
    update_post_form = PostForm()
    if update_post_form.validate_on_submit():
        update_post(post)
        flash("Post has been updated.", "success")
        return redirect(request.form["url"])


# Delete


@posts_blueprint.route("/<int:post_id>/delete", methods=["POST"])
def delete_post_route(post_id):
    delete_post(post_id)
    flash("Post has been deleted.", "success")
    return redirect(request.form["url"])

WebApp/store/routes.py
from flask import Blueprint, render_template, redirect, url_for, abort, request, flash
from flask_login import current_user
from WebApp.models import Cart
from WebApp.store.forms import ItemForm, CheckoutForm
from WebApp.store.utils import (
    get_all_products,
    get_product,
    search_products,
    add_item_to_cart,
    get_cart_and_cart_item_with_total_and_quantity,
    get_cart_item_and_form,
    get_list_of_cart_items,
    update_cart_items,
    update_cart_item,
    delete_cart_item,
    delete_all_cart_items,
    process_order,
)


store_blueprint = Blueprint(
    "store", __name__, url_prefix="/store", template_folder="templates"
)


@store_blueprint.route("search", methods=["GET", "POST"])
def search():
    search = request.form["search"]
    products = search_products(search)
    return render_template("store/products.html", title="Store", products=products)


@store_blueprint.route("")
def products():
    products = get_all_products()
    return render_template("store/products.html", title="Store", products=products)


@store_blueprint.route("<int:product_id>", methods=["GET", "POST"])
def product(product_id):
    product = get_product(product_id)
    form = ItemForm()
    if form.validate_on_submit():
        add_item_to_cart(product)
        flash(
            f"{form.quantity.data} x {product.name} ({form.size.data}) added to your cart.",
            "success",
        )
        return redirect(url_for("store.products", product_id=product_id))
    return render_template(
        "store/product-item.html", title=product.name, product=product, form=form
    )


@store_blueprint.route("cart")
def cart():
    cart, cart_items = get_cart_and_cart_item_with_total_and_quantity()
    return render_template(
        "store/cart.html", title="Cart", cart=cart, cart_items=cart_items
    )


@store_blueprint.route("cart/update", methods=["POST"])
def cart_update():
    update_cart_items()
    return redirect(url_for("store.cart"))


@store_blueprint.route("cart/<item_id>", methods=["GET", "POST"])
def cart_item_update(item_id):
    item, form = get_cart_item_and_form(item_id)
    if form.validate_on_submit():
        update_cart_item(item)
        return redirect(url_for("store.cart"))
    return render_template(
        "store/product-item.html", title="Edit Cart Item", item=item, form=form
    )


@store_blueprint.route("cart/<item_id>/delete", methods=["POST"])
def cart_delete_item(item_id):
    delete_cart_item(item_id)
    return redirect(url_for("store.cart"))


@store_blueprint.route("cart/clear", methods=["POST"])
def cart_clear():
    delete_all_cart_items()
    return redirect(url_for("store.cart"))


@store_blueprint.route("cart/submit", methods=["POST"])
def submit_cart():
    cart_items = get_list_of_cart_items()
    if cart_items:
        return redirect(url_for("store.checkout"))
    else:
        flash("Add items to cart to checkout.", "danger")
        return redirect(url_for("store.cart"))


@store_blueprint.route("checkout", methods=["GET", "POST"])
def checkout():
    form = CheckoutForm()
    if form.validate_on_submit():
        process_order()
        flash("Order has been processsed.", "success")
        return redirect(url_for("store.checkout_success"))
    return render_template("store/checkout.html", title="Checkout", form=form)


@store_blueprint.route("checkout/success")
def checkout_success():
    if request.referrer:
        return render_template("store/checkout_success.html", title="Checkout")
    else:
        abort(400)

WebApp/users/routes.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    session,
    flash,
    abort,
)
from flask_login import login_user, current_user, logout_user, login_required
from WebApp.models import User
from WebApp.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from WebApp.users.utils import (
    confirm_email,
    register_user,
    update_user_info,
    send_reset_request_email,
    login_user,
    set_new_password,
    handle_login,
)
from WebApp.posts.forms import PostForm
from WebApp.posts.utils import add_post, get_paginated_user_posts, get_redirects
from WebApp.store.utils import create_anon_cart

users_blueprint = Blueprint("users", __name__, template_folder="templates")


@users_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        register_user()
        return redirect(url_for("users.login"))
    return render_template("users/register.html", title="Register", form=form)


@users_blueprint.route("/confirm_email/<token>", methods=["GET", "POST"])
def confirm_email_token(token):
    user = User.verify_confirm_email_token(token)
    if user is None:
        flash("Invalid or expired token.", "warning")
        return redirect(url_for("users.register"))
    confirm_email(user)
    return redirect(url_for("posts.posts"))


@users_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        return handle_login()
    return render_template("users/login.html", title="Login", form=form)


@users_blueprint.route("/logout")
def logout():
    logout_user()
    session.clear()
    create_anon_cart()
    flash("You have been logged out.", "success")
    return redirect(url_for("main.home"))


@users_blueprint.route("/<string:username>", methods=["GET", "POST"])
@users_blueprint.route("/<string:username>/posts", methods=["GET", "POST"])
def user_posts(username):
    create_post_form = PostForm()
    if create_post_form.validate_on_submit():
        add_post()
        return redirect(request.form["url"])
    user = User.query.filter_by(username=username).first_or_404()
    posts = get_paginated_user_posts(user)
    update_post_form = PostForm()
    redirect_dict = get_redirects(username=username)
    return render_template(
        "posts/user-posts/view.html",
        title="Home",
        user=user,
        create_post_form=create_post_form,
        update_post_form=update_post_form,
        create_redirect=redirect_dict["create"],
        update_redirect=redirect_dict["update"],
        delete_redirect=redirect_dict["delete"],
        posts=posts,
    )


@users_blueprint.route("/settings", methods=["GET", "POST"])
@login_required
def account_settings():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        update_user_info()
        return redirect(
            url_for("users.account_settings", username=current_user.username)
        )
    form.username.data = current_user.username
    form.email.data = current_user.email
    form.subscription_status.data = current_user.subscription_status
    return render_template(
        "users/account/settings/view.html",
        title="Account",
        user=current_user,
        form=form,
    )


@users_blueprint.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        send_reset_request_email()
        return redirect(url_for("users.login"))
    return render_template(
        "users/reset_request.html", title="Reset Password", form=form
    )


@users_blueprint.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_password_token(token)
    if user is None:
        flash("Invalid or expired token.", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        set_new_password(user)
        return redirect(url_for("posts.posts"))
    return render_template("users/reset-token.html", title="Reset Password", form=form)

WebApp/templates/layout-components/bootstrap4.html
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

WebApp/templates/layout-components/debug.html
<p>
    Endpoint <br />
    {{request.endpoint}}
</p>

<p>
    User Id: {{current_user.id}}<br />
    Authenticated: {{current_user.is_authenticated}}
</p>

{% if form and form.errors %}
<p>
    Errors<br />
    {{ form.errors}}
</p>
{% endif %}

{% if session['cart'] %}
<p>
    Cart<br />
    {{session['cart']}}
</p>

{% endif %}

<p>{{session}}</p>

WebApp/templates/layout-components/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
    {% endif %}
{% endwith %}

WebApp/templates/layout-components/google-icons.html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

WebApp/templates/layout-components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-steel">
	<div class="container">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
			aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="{{url_for('main.home')}}">Web App</a>
		<div class="collapse navbar-collapse" id="navbarToggle">
			<div class="navbar-nav mr-auto">

				<!-- <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
						data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Components
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{{ url_for('posts.posts') }}">Posts</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{{ url_for('store.products') }}">Shop</a>
						<a class="dropdown-item" href="{{ url_for('store.cart') }}">Cart</a>
					</div>
				</li> -->
				<li>
					<a class="nav-item nav-link" href="{{ url_for('store.products') }}">Shop</a>
				</li>
				<li>
					<a class="nav-item nav-link" href="{{ url_for('store.cart') }}">Cart</a>
				</li>
				<li>
					<a class="nav-item nav-link" href="{{ url_for('posts.posts') }}">Posts</a>
				</li>
				<li>
					<a class="nav-item nav-link" href="{{ url_for('main.marketing') }}">Marketing</a>
				</li>
				<li>
					<a class="nav-item nav-link" href="{{ url_for('main.contact') }}">Contact Us</a>
				</li>
			</div>
			<div class="navbar-nav">
				{% if current_user.is_authenticated %}
				{% else %}
				<li>
					<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
				</li>
				<li>
					<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
				</li>
				{% endif %}
			</div>
			{% if current_user.is_authenticated %}
			<div class="navbar-nav">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
						data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<img class="rounded-circle account-img p-0 m-0" style='height:2em; width: 2em;'
							src="{{ url_for('static', filename='images/profile_pics/' + current_user.image_file) }}">
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item"
							href="{{ url_for('users.user_posts', username=current_user.username) }}">
							{{current_user.username}}
						</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item"
							href="{{ url_for('users.user_posts', username=current_user.username) }}">
							View Profile
						</a>
						<a class="dropdown-item" href="{{ url_for('users.account_settings') }}">
							Account Settings
						</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
					</div>
				</li>
			</div>
			{% endif %}
			<!-- <form class="ml-3 form-inline my-2 my-lg-0">
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
			</form> -->
		</div>
	</div>
</nav>