WebApp/store/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SelectField,
    DateField,
    RadioField,
    BooleanField,
    SubmitField,
)
from wtforms.validators import DataRequired, Email

default_option = [(None, "Select")]

size_choices = [
    (None, "Select Size"),
    ("X-Small", "X-Small"),
    ("Small", "Small"),
    ("Medium", "Medium"),
    ("Large", "Large"),
    ("X-Large", "X-Large"),
]

quantity_choices = default_option + [(str(n), n) for n in range(1, 11)]


class ItemForm(FlaskForm):
    quantity = SelectField(
        "Quantity", choices=quantity_choices, validators=[DataRequired()]
    )
    size = SelectField("Size", choices=size_choices, validators=[DataRequired()])
    submit = SubmitField("Submit")


provinces = [
    ("--", "--"),
    ("Alberta", "AB"),
    ("British Columbia", "BC"),
    ("Manitoba", "MB"),
    ("New Brunswich", "NB"),
    ("Newfoundland and Labrador", "NL"),
    ("Northwest Territories", "NT"),
    ("Nova Scotia", "NS"),
    ("Nunavat", "NU"),
    ("Ontario", "ON"),
    ("Prince Edward Island", "PEI"),
    ("Quebec", "QC"),
    ("Saskatchewan", "SK"),
    ("Yukon", "YT"),
]

countries = [("--", "--"), ("Canada", "CA")]


class CheckoutForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    newsletter_sub = BooleanField(
        "Keep me up to date on news and exclusive offers", default=True
    )
    shipping_first_name = StringField("First Name", validators=[DataRequired()])
    shipping_last_name = StringField("Last Name", validators=[DataRequired()])
    shipping_address = StringField("Address", validators=[DataRequired()])
    shipping_address_unit = StringField("Apartment")
    shipping_city = StringField("City", validators=[DataRequired()])
    shipping_region = SelectField(
        "State/Province/Region",
        choices=provinces,
        default="--",
        validators=[DataRequired()],
    )
    shipping_postal_code = StringField("Postal Code", validators=[DataRequired()])
    shipping_country = SelectField(
        "Country", choices=countries, default="--", validators=[DataRequired()]
    )
    shipping_phone_number = StringField("Phone Number", validators=[DataRequired()])

    shipping_method = RadioField(
        "Shipping Method",
        choices=[
            ("Standard", "Standard ( 7 - 14 Business Days )"),
            ("Express", "Express ( 1 - 7 Business Days"),
        ],
        validators=[DataRequired()],
        default="Standard",
    )

    card_number = StringField("Card Number", validators=[DataRequired()])
    card_name = StringField("Name on Card", validators=[DataRequired()])
    card_expiration_month = StringField("Exp. Month", validators=[DataRequired()])
    card_expiration_year = StringField("Exp. Year", validators=[DataRequired()])

    same_as_shipping = BooleanField("Same as shipping addess")

    billing_first_name = StringField("First Name", validators=[DataRequired()])
    billing_last_name = StringField("Last Name", validators=[DataRequired()])
    billing_address = StringField("Address", validators=[DataRequired()])
    billing_address_unit = StringField("Apartment")
    billing_city = StringField("City", validators=[DataRequired()])
    billing_region = SelectField(
        "State/Province/Region", choices=provinces, default="--"
    )
    billing_postal_code = StringField("Postal Code", validators=[DataRequired()])
    billing_country = SelectField("Country", choices=countries, default="--")
    billing_phone_number = StringField("Phone Number", validators=[DataRequired()])

    submit = SubmitField("Submit")

WebApp/store/routes.py
from flask import Blueprint, render_template, redirect, url_for, abort, request, flash
from flask_login import current_user
from WebApp.models import Cart
from WebApp.store.forms import ItemForm, CheckoutForm
from WebApp.store.utils import (
    get_all_products,
    get_product,
    search_products,
    add_item_to_cart,
    get_cart_and_cart_item_with_total_and_quantity,
    get_cart_item_and_form,
    get_list_of_cart_items,
    update_cart_items,
    update_cart_item,
    delete_cart_item,
    delete_all_cart_items,
    process_order,
)


store_blueprint = Blueprint(
    "store", __name__, url_prefix="/store", template_folder="templates"
)


@store_blueprint.route("search", methods=["GET", "POST"])
def search():
    search = request.form["search"]
    products = search_products(search)
    return render_template("store/products.html", title="Store", products=products)


@store_blueprint.route("")
def products():
    products = get_all_products()
    return render_template("store/products.html", title="Store", products=products)


@store_blueprint.route("<int:product_id>", methods=["GET", "POST"])
def product(product_id):
    product = get_product(product_id)
    form = ItemForm()
    if form.validate_on_submit():
        add_item_to_cart(product)
        flash(
            f"{form.quantity.data} x {product.name} ({form.size.data}) added to your cart.",
            "success",
        )
        return redirect(url_for("store.products", product_id=product_id))
    return render_template(
        "store/product-item.html", title=product.name, product=product, form=form
    )


@store_blueprint.route("cart")
def cart():
    cart, cart_items = get_cart_and_cart_item_with_total_and_quantity()
    return render_template(
        "store/cart.html", title="Cart", cart=cart, cart_items=cart_items
    )


@store_blueprint.route("cart/update", methods=["POST"])
def cart_update():
    update_cart_items()
    return redirect(url_for("store.cart"))


@store_blueprint.route("cart/<item_id>", methods=["GET", "POST"])
def cart_item_update(item_id):
    item, form = get_cart_item_and_form(item_id)
    if form.validate_on_submit():
        update_cart_item(item)
        return redirect(url_for("store.cart"))
    return render_template(
        "store/product-item.html", title="Edit Cart Item", item=item, form=form
    )


@store_blueprint.route("cart/<item_id>/delete", methods=["POST"])
def cart_delete_item(item_id):
    delete_cart_item(item_id)
    return redirect(url_for("store.cart"))


@store_blueprint.route("cart/clear", methods=["POST"])
def cart_clear():
    delete_all_cart_items()
    return redirect(url_for("store.cart"))


@store_blueprint.route("cart/submit", methods=["POST"])
def submit_cart():
    cart_items = get_list_of_cart_items()
    if cart_items:
        return redirect(url_for("store.checkout"))
    else:
        flash("Add items to cart to checkout.", "danger")
        return redirect(url_for("store.cart"))


@store_blueprint.route("checkout", methods=["GET", "POST"])
def checkout():
    form = CheckoutForm()
    if form.validate_on_submit():
        process_order()
        flash("Order has been processsed.", "success")
        return redirect(url_for("store.checkout_success"))
    return render_template("store/checkout.html", title="Checkout", form=form)


@store_blueprint.route("checkout/success")
def checkout_success():
    if request.referrer:
        return render_template("store/checkout_success.html", title="Checkout")
    else:
        abort(400)

WebApp/store/templates/store/cart-items.html
{% for item in cart_items %}
<div class='row pt-3 pb-3'>
	<div class='col-3 col-lg-3'>
		<img class="img-fluid mb-3"
			src="{{ url_for('static', filename='images/store/products/' + item.product.image_file) }}">
	</div>
	<div class='col-9 col-lg-6'>
		{{item.product.name}}<br />
		Item: {{ item.product.code }}<br />
		Price: ${{ '%0.2f' | format(item.product.price) }} <br />
		Size: {{ item.size }}<br />
		Color: {{ item.product.color }}<br />
		<a class='btn btn-link' href='{{ url_for("store.cart_item_update", item_id=item.id ) }}'>Edit</a>|
		<form action='{{ url_for("store.cart_delete_item", item_id=item.id) }}' method='POST' style='display: inline;'>
			<input class='btn btn-link' type='submit' value='Remove'>
		</form>|
		<form class='d-inline' method='post' action='{{ url_for("store.cart_update") }}'>
			<select class='custom-select d-inline' id='{{item.id}}' name='{{ item.id }}'
				style='width: 4em; text-align-last: center'>
				{% for value in range(1,11) %}
				<option value='{{value}}' {% if item.quantity==value %} selected {% endif %}>{{value}}</option>
				{% endfor %}
			</select>
		</form>
		<script type="text/javascript">
			$("#{{item.id}}").change(function () {
				this.form.submit();
			});
		</script>
	</div>
</div>
<hr>
{% else %}
<h6 align='center'>Is currently empty...</h6>
{% endfor %}

WebApp/store/templates/store/cart.html
{% extends 'layout.html' %}
{% block content %}
<div class='content-section'>
	<h1 class='text-center'>Your Cart</h1>
	<hr />

	{% include 'store/cart-items.html' %}
	<h5 align='right'>Subtotal ({{cart.quantity}} items): CDN${{ '%0.2f' | format(cart.total|float)  }}</h5>
	<hr />

	<div class='clearfix'>
		<div class='float-right'>

			<form class='d-inline' method='post' action='{{ url_for("store.cart_clear") }}'>
				<input type='submit' value='Clear Cart' class='btn btn-primary'>
			</form>

			<form class='d-inline' method='POST' action='{{url_for("store.submit_cart")}}'>
				<input type='submit' value='Checkout' class='btn btn-primary'>
			</form>

		</div>
	</div>

</div>
{% endblock %}

WebApp/store/templates/store/checkout.html
{% extends 'layout.html' %}
{% block content %}

{% include 'forms/checkout-form.html' %}
<script>
    $('#submit').click(function () {
        if ($('#same_as_shipping').is(":checked")) {
            $('#billing_first_name').val($("#shipping_first_name").val());
            $('#billing_last_name').val($("#shipping_last_name").val());
            $('#billing_address').val($("#shipping_address").val());
            $('#billing_address_unit').val($("#shipping_address_unit").val());
            $('#billing_city').val($("#shipping_city").val());
            $('#billing_region').val($("#shipping_region").val());
            $('#billing_country').val($("#shipping_country").val());
            $('#billing_address_unit').val($("#shipping_address_unit").val());
            $('#billing_postal_code').val($("#shipping_postal_code").val());
            $('#billing_postal_code').val($("#shipping_postal_code").val());
            $('#billing_phone_number').val($("#shipping_phone_number").val());
        }
    });
</script>

{% endblock %}

WebApp/store/templates/store/checkout_success.html
{% extends 'layout.html' %}
{% block content %}
<p>
    Thanks for your interest in our products. Blah blah blah.
</p>
{% endblock %}

WebApp/store/templates/store/product-item.html
{% extends 'layout.html' %}
{% block content %}
{% if request.endpoint == 'store.cart_item_update' %}
<h1>Edit Cart Item</h1>
<hr />
{% endif %}
<div class="row">
	<div class="col-md-6">
		<img class='img-fluid' {% if item %}
			src="{{ url_for('static', filename='images/store/products/' + item.product.image_file) }}">
		{% else %}
		src="{{ url_for('static', filename='images/store/products/' + product.image_file) }}">
		{% endif %}
	</div>
	<div class="col-md-6">
		<h3>{{ item.product.name if item else product.name}}</h3>
		<h5>${{'%0.2f' | format(item.product.price if item else product.price|float)}} CAD</h5>
		<hr />
		<p>{{ item.product.description if item else product.price }}</p>
		<hr />
		{% include 'forms/product-form.html' %}
	</div>
</div>
{% endblock %}

WebApp/store/templates/store/products.html
{% extends "layout.html" %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/store.css') }}">
<div class='mb-3'>
    <form method='POST' action="{{url_for('store.search')}}" id='search'>
        <div class="input-group">
            <input type="text" name='search' class="form-control" placeholder="Search for.." autocomplete="off">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>


<div class="products row">
    {% for product in products %}
    <a href="{{url_for('store.product', product_id=product.id) }}" class="btn col-sm-6 col-lg-4 col-xl-3">
        <img class="img-fluid mb-3"
            src="{{ url_for('static', filename='images/store/products/' + product.image_file) }}">
        <h5>{{product.name}}</h5>
        ${{ '%0.2f' | format(product.price | float) }} CAD
    </a>
    {% endfor %}
</div>

{% endblock %}